### ISSUE TITLE
KubernetesSeedProvider incompatible with higher Cassandra 3.11 patch versions

### ISSUE THREAD

**Issue by alangibson01** [sky-uk/cassandra-operator#227]
### What is the bug being reported?
It appears that KubernetesSeedProvider is incompatible with Cassandra 3.11 patch versions higher than 3.11.2:

```
ERROR [main] 2020-03-11 14:35:52,984 CassandraDaemon.java:774 - Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: com.sky.core.operators.cassandra.seedprovider.KubernetesSeedProvider
Fatal configuration error; unable to start server.  See log for stacktrace.
	at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:939) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:338) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:153) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:137) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:675) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:619) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
```

### What would be the expected behavior?
I would expect KubernetesSeedProvider to work with all patch versions of the same minor version.

### If repeatable, how can we reproduce this issue?
Apply the following cluster definition and observe the logs of the `cassandra` container in the first pod which is scheduled:

```yaml
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: test-cassandra
  namespace: test-cassandra
spec:
  dc: dc1
  pod:
    cpu: "0"
    image: cassandra:3.11
    memory: 2000Mi
    storageSize: 10Gi
  racks:
  - name: a
    replicas: 1
    storageClass: ${SOME_STORAGE_CLASS}
    zone: ${SOME_ZONE}
```

### Workaround, if known
Explicitly specify a working patch version, e.g. `cassandra:3.11.2`
 
### Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:
* Cassandra operator docker image: v0.70.1-alpha1

**Comment by Bez625** [comment]
Given we have 3.11.8 in ccl and that seems fine I think we can close this:
```
cassandra@ccl-cassandra-c-0:/$ nodetool version
ReleaseVersion: 3.11.8
```
I double checked with @alangibson01 and he couldnt think of a reason to keep it open. We speculate this was a particular issue with 3.11.6.
