### ISSUE TITLE
Cluster config modification events are not generated 

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#34]
### Describe the bug

Cluster config modification events are sometimes not appearing as Kubernetes events even though the operator code clearly is executed. This happens infrequently when running tests against either a DIND cluster or dev, but never when the failing tests are run in isolation.

This perhaps suggests that some events get overwritten or dropped. This is surprising given that the `k8s.io/client-go/tools/record/EventRecorder` can queue up to 1000 events and logs an error when the same even has reached the max retry count.

Failing test: Allowable cluster modifications > cluster config file changes
```
[10] Allowable cluster modifications
[10] /home/sebbonnet/gowork/src/github.com/sky-uk/core-operators/cassandra-operator/test/e2e/parallel/modification/modification_test.go:50
[10]   cluster config file changes
[10]   /home/sebbonnet/gowork/src/github.com/sky-uk/core-operators/cassandra-operator/test/e2e/parallel/modification/modification_test.go:175
[10]     should trigger a rolling restarts of the cluster stateful set when the custom config file is deleted [It]
[10]     /home/sebbonnet/gowork/src/github.com/sky-uk/core-operators/cassandra-operator/test/e2e/parallel/modification/modification_test.go:249
[10]
[10]     Timed out after 30.001s.
[10]     Expected event {Normal ClusterUpdate Custom config deleted for cluster test-cassandra-operator.mycluster-fdevi 2019-03-22 18:03:50.090478874 +0000 GMT m=+251.420548413}. Actual event: [{{ } {mycluster-fdevi.158e59c9b7eb31e1  test-cassandra-operator /api/v1/namespaces/test-
cassandra-operator/events/mycluster-fdevi.158e59c9b7eb31e1 69d314af-4ccc-11e9-88c4-0624fb7941ea 507389776 0 2019-03-22 18:00:44 +0000 GMT <nil> <nil> map[] map[] [] nil [] } 
[...]
[10]     /home/sebbonnet/gowork/src/github.com/sky-uk/core-operators/cassandra-operator/test/e2e/parallel/modification/modification_test.go:265
```
 ### Expected Behavior
The tests should consistently pass regardless of whether they are run in parallel or not.

 ### Steps to Reproduce
1. `cd $GOPATH/src/github.com/sky-uk/cassandra-operator/`
2. `make install-all`
3. `cd cassandra-operator`
4. `E2E_TEST=test/e2e/parallel/modification make e2e-test`

 ### Your Environment
* Kubernetes version: `1.10.12`
* OS: Fedora 28, 12 cores
* Cassandra operator docker image: `skyuk/cassandra-operator:v0.70.0-alpha`
* Cassandra cluster definition: those created by the tests for this git revision `v0.70.0-alpha`

**Comment by sebbonnet** [comment]
We're getting a panic on cluster modification when snapshot properties are being compared:
```
  | 2019-06-11 10:33:41.775 UTC | time="2019-06-11T10:33:41Z" level=debug msg="Cluster update detected for cassandra-operator-stubbed-functional.mycluster-47evy, old: {<nil> [{a eu-west-1a standard-zone-a 1}] 0xc000470aff {0xc000090780 0xc000090790 {{0 0} {<nil>} 0 DecimalSI} {{1073741824 0} {<nil>} 1Gi BinarySI} {{0 0} {<nil>} 0 DecimalSI} 0xc0003826c0 0xc000382700} 0xc0001e0300} \nnew: {<nil> [{a eu-west-1a standard-zone-a 1}] 0xc00070fd7f {0xc00052d000 0xc00052d040 {{0 0} {<nil>} 0 DecimalSI} {{1073741824 0} {<nil>} 1Gi BinarySI} {{0 0} {<nil>} 0 DecimalSI} 0xc000472f00 0xc000472f40} 0xc0003ea680}"
  | 2019-06-11 10:33:41.778 UTC | panic: runtime error: invalid memory address or nil pointer dereference
  | 2019-06-11 10:33:41.778 UTC | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8af875]
  | 2019-06-11 10:33:41.778 UTC | goroutine 83 [running]:
  | 2019-06-11 10:33:41.778 UTC |  
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations/receiver.go:83 +0x3fc
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/apis/cassandra/v1alpha1/types.go:171 +0x65
  | 2019-06-11 10:33:41.778 UTC | github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations.(*Receiver).operationsToExecute(0xc0002a7700, 0xc000345410, 0x30, 0x129cee0, 0xc00053be98)
  | 2019-06-11 10:33:41.778 UTC | created by github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/dispatcher.(*dispatcher).Dispatch
  | 2019-06-11 10:33:41.778 UTC | github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations.(*Receiver).operationsForUpdateCluster(0xc0002a7700, 0xc000106480, 0xc0001c3d40, 0xe, 0x1, 0xc0002de1d8)
  | 2019-06-11 10:33:41.778 UTC | github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/dispatcher.(*dispatcher).start(0xc000344030, 0xc0003e2240, 0xc000314ab0, 0xc0002de180)
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/dispatcher/dispatcher.go:59 +0x2c0
  | 2019-06-11 10:33:41.778 UTC | github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/apis/cassandra/v1alpha1.SnapshotPropertiesUpdated(0xc0001e0300, 0xc0003ea680, 0x0)
  | 2019-06-11 10:33:41.778 UTC | github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations.(*Receiver).Receive(0xc0002a7700, 0xc000345410)
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/dispatcher/dispatcher.go:81 +0x42
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations/receiver.go:152 +0x2ee
  | 2019-06-11 10:33:41.778 UTC | /home/sebbonnet/gowork/src/github.com/sky-uk/cassandra-operator/cassandra-operator/pkg/operator/operations/receiver.go:67 +0x4d
  | 2019-06-11 10:33:42.212 UTC | Jun 11 10:33:42 cassandra-operator-85c79c9855-mwwzm syslog-ng[13]: syslog-ng shutting down; version='3.5.6'
  | 2019-06-11 10:33:42.214 UTC | Jun 11 10:33:42 cassandra-operator-85c79c9855-mwwzm syslog-ng[13]: EOF on control channel, closing connection;
  | 2019-06-11 10:34:11.024 UTC | Jun 11 10:34:11 cassandra-operator-85c79c9855-mwwzm syslog-ng[13]: syslog-ng starting up; version='3.5.6'
  | 2019-06-11 10:34:12.001 UTC | Jun 11 10:34:12 cassandra-operator-85c79c9855-mwwzm syslog-ng[13]: EOF on control channel, closing connection;
  | 2019-06-11 10:34:12.012 UTC | Jun 11 10:34:12 cassandra-operator-85c79c9855-mwwzm cron[23]: (CRON) INFO (pidfile fd = 3)
  | 2019-06-11 10:34:12.013 UTC | Jun 11 10:34:12 cassandra-operator-85c79c9855-mwwzm cron[23]: (CRON) INFO (Running @reboot jobs)
  | 2019-06-11 10:34:12.018 UTC | time="2019-06-11T10:34:12Z" level=info msg="Starting Cassandra operator with config: &{5s 5s true}"

**Comment by sebbonnet** [comment]
I was expecting this test `snapshot_test.go: when a scheduled snapshot is modified should create a kubernetes job with the new properties and delete the old one` to fail in the build, but digging a little further I found that is not the case due to the way the Snapshot properties comparison is done. As the comparison stops as soon as one property is different, the test is not failing because the schedule is the only difference in the Snapshots and is also the first property check, therefore avoiding the comparison causing panic.

The panic actually happens after the test completes during the cleanup.
Deleting the cassandra resource triggers an UPDATE_CLUSTER event when it should be a delete. 
Deleting the same cassandra resource via kubectl does however trigger a DELETE_CLUSTER event as expected. 
Where is the difference? 
It turns out the cleanup code deletes with a foreground propagation policy when kubectl uses the default policy for `cassandra` type which appears to be a background propagation policy. In fact changing the code to delete the `cassandra` resource with no propagation policy or one of default does result in a DELETE_CLUSTER event. Setting the propagation policy to orphans triggers an UPDATE_CLUSTER similarly to the foreground policy

**Comment by sebbonnet** [comment]
Now the reason why this issue is not seen on travis is due to the lack of tests parallelisation.
The Travis environment we use comes with 2 cpu cores whereas my laptop has 12, so there will be many more tests running in parallel on my laptop therefore increasing the side effect of the test cleanup on other tests.

**Comment by sebbonnet** [comment]
I'm still seeing this issue happening intermittenly. The panic I mentioned above isn't related, as the problem still persists after the fix.

**Comment by sebbonnet** [comment]
I've added additional logging to try narrow down the issue (see [intermittent-events-loss ](https://github.com/sky-uk/cassandra-operator/tree/intermittent-events-loss)):
- log using a custom LoggingEventRecorder that delegates to the real EventRecorder, which should print a log line before and after the event is recorded - recording actually distributes the even to all watchers
- log using the build-in logging watcher using `EventBroadcaster.StartLogging`
- log using a custom LoggingEventSink that delegates to the real EventSink watcher, which should print a log line before and after the event is posted to the apiserver  

Here is the sequence of events I would expect to see:
```
time="2019-06-14T18:05:29Z" level=debug msg="Event received" key=cassandra-operator-stubbed-functional.mycluster-gezll-config type=DELETE_CUSTOM_CONFIG                                                                                                                                   
time="2019-06-14T18:05:29Z" level=info msg="Event will trigger 1 operations" key=cassandra-operator-stubbed-functional.mycluster-gezll-config type=DELETE_CUSTOM_CONFIG                                                                                                                   
time="2019-06-14T18:05:29Z" level=debug msg="Executing operation remove custom config for cluster cassandra-operator-stubbed-functional.mycluster-gezll" key=cassandra-operator-stubbed-functional.mycluster-gezll-config type=DELETE_CUSTOM_CONFIG                                       
time="2019-06-14T18:05:29Z" level=debug msg="LoggingEventRecorder Recording eventf type Normal, reason: ClusterUpdate, msg: Custom config deleted for cluster %s, args: [cassandra-operator-stubbed-functional.mycluster-gezll]"                                                          
time="2019-06-14T18:05:29Z" level=debug msg="LoggingEventRecorder Done Recording eventf type Normal, reason: ClusterUpdate, msg: Custom config deleted for cluster %s, args: [cassandra-operator-stubbed-functional.mycluster-gezll]"                                                     
time="2019-06-14T18:05:29Z" level=info msg="Applying update for rack a in cluster cassandra-operator-stubbed-functional.mycluster-gezll"                                                                                                                                                  
time="2019-06-14T18:05:29Z" level=debug msg="LoggingEventSink Creating event mycluster-gezll.15a822cbcfc99f00, reason: ClusterUpdate, msg: Custom config deleted for cluster cassandra-operator-stubbed-functional.mycluster-gezll"                                                       
time="2019-06-14T18:05:29Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Cassandra\", Namespace:\"cassandra-operator-stubbed-functional\", Name:\"mycluster-gezll\", UID:\"d77fbd4a-8ece-11e9-89c9-02fcee9bd304\", APIVersion:\"core.sky.uk/v1alpha1\", ResourceVersion:\"603815752\",
 FieldPath:\"\"}): type: 'Normal' reason: 'ClusterUpdate' Custom config deleted for cluster cassandra-operator-stubbed-functional.mycluster-gezll"                                                                                                                                        
time="2019-06-14T18:05:29Z" level=debug msg="LoggingEventSink Created event mycluster-gezll.15a822cbcfc99f00, reason: ClusterUpdate, msg: Custom config deleted for cluster cassandra-operator-stubbed-functional.mycluster-gezll, error: <nil>"                     
```

However, nothing is being logged by the `LoggingEventSink` in a failure scenario which explains why the events never make it to the apiserver
```
time="2019-06-14T17:57:51Z" level=debug msg="Event received" key=cassandra-operator-stubbed-functional.mycluster-odxqu-config type=DELETE_CUSTOM_CONFIG
time="2019-06-14T17:57:51Z" level=debug msg="LoggingEventRecorder Recording eventf type Normal, reason: ClusterUpdate, msg: Custom config deleted for cluster %s, args: [cassandra-operator-stubbed-functional.mycluster-odxqu]"
time="2019-06-14T17:57:51Z" level=debug msg="LoggingEventRecorder Done Recording eventf type Normal, reason: ClusterUpdate, msg: Custom config deleted for cluster %s, args: [cassandra-operator-stubbed-functional.mycluster-odxqu]"
time="2019-06-14T17:57:51Z" level=info msg="Applying update for rack a in cluster cassandra-operator-stubbed-functional.mycluster-odxqu"
time="2019-06-14T17:57:51Z" level=info msg="Event will trigger 1 operations" key=cassandra-operator-stubbed-functional.mycluster-odxqu-config type=DELETE_CUSTOM_CONFIG
time="2019-06-14T17:57:51Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Cassandra\", Namespace:\"cassandra-operator-stubbed-functional\", Name:\"mycluster-odxqu\", UID:\"8ab22128-8ecd-11e9-ad6a-0624fb7941ea\", APIVersion:\"core.sky.uk/v1alpha1\", ResourceVersion:\"603807132\", FieldPath:\"\"}): type: 'Normal' reason: 'ClusterUpdate' Custom config deleted for cluster cassandra-operator-stubbed-functional.mycluster-odxqu"
```

The watchers have a default max queue length of 1000 with a DropIfChannelFull policy, but it's hard to see how this could be the problem given that we're not sending this many events. 
Events that fail to be written to the sink should produce some error logs for each attempt and also log an error after the max number of retries (12 every 10s) - perhaps we are not waiting long enough to see this error? I'll change the test to wait for 180s.

**Comment by sebbonnet** [comment]
We're getting rate limited to 25 events per `cassandra` object: https://github.com/kubernetes/client-go/blob/v11.0.0/tools/record/events_cache.go#L48
When we do, the event is getting dropped without warning: https://github.com/kubernetes/client-go/blob/v11.0.0/tools/record/event.go#L136

The spam key is defined per `cassandra` object (event source + involved object), so even if some messages were aggregated it wouldn't help. I would have thought having the spam key defined on the aggregated key would have been better, but that probably complicates the calculation quite a bit.
Being limited to 25 events (then 1 new every 5mins) per involved object is quite aggressive and doesn't work well with our design where rolling updates generate 1 or more cluster update events + 1 every 5s for each statefulset until all the pods have been updated. As each pod update takes about 1m to restart on the new config, the rate limitation will quickly be reached on small clusters, let alone large ones. 

Potential options to remedy the problem:
- change the events involved object to something more fine-grained (e.g. pod)
- define an event recorder per `cassandra` definition , so we can increase the rate limit configuration based on the cluster size. It would help if we could customise the spamming option like this:  
https://github.com/kubernetes/client-go/commit/060f7d3455c314e265b67d1a05644dabc64350e7#diff-39f04505ddbdf6d6b3f2655e78453179
- implement an exponential back-off delay per event type, `WaitingForStatefulSetChange` being by far the most recurrent.

I'm not keen on the first option as it makes it hard to find all events for a `cassandra` cluster - it's much easier if all cluster events are associated the same `cassandra` object.
I think option 2 alone might be enough and would scale similarly to option 1. Besides I would expect to see events being aggregated if we increase the spam limit. If that's not enough, we could look into Option 3 to reduce events of type `WaitingForStatefulSetChange`.

Custom logging added [here](https://github.com/sky-uk/cassandra-operator/commit/44952ba52a754a7768cee451a04f4cf76f897118) shows the problem:
```
level=info msg="Filter event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, key: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1"
level=debug msg="Event(v1.ObjectReference{Kind:\"Cassandra\", Namespace:\"cassandra-operator-stubbed-functional\", Name:\"mycluster-maqy0\", UID:\"e75794d3-911c-11e9-ad6a-0624fb7941ea\", APIVersion:\"core.sky.uk/v1alpha1\", ResourceVersion:\"606501708\", FieldPath:\"\"}): type: 'Normal' reason: 'ClusterUpdate' Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0"
level=info msg="Filter event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, spam record found for key: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1"
level=info msg="Aggregate event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, key: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdateCustom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, aggregated: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdate, interval: 9223372036854775807, maxInterval: 600000000000"
level=info msg="recordToSink Skipping event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, count: 1"
level=info msg="Aggregate event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, key: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdateCustom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, aggregated: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdate"
level=info msg="Aggregate event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, key: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdateCustom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, aggregated: cassandra-operatorCassandracassandra-operator-stubbed-functionalmycluster-maqy0e75794d3-911c-11e9-ad6a-0624fb7941eacore.sky.uk/v1alpha1NormalClusterUpdate, localKeys: 1, maxEvents: 10"
level=info msg="Filter event mycluster-maqy0.15a9097c05edf161, reason: ClusterUpdate, message: Custom config created for cluster cassandra-operator-stubbed-functional.mycluster-maqy0, filtered true"
```

**Comment by sebbonnet** [comment]
There is no need to define an event recorder per `cassandra` resource, as each cluster would have up to 3 racks - most providers offering up to 3 zones per region. So if we cut down the number of events per statefulset to 2 (one when waiting, one when done waiting) we will stay well within the 25 events limit.
Besides I don't think there is much value in printing the "wait" event continuously, as users would probably want to look at their statefulset / pod level events for better granularity.
I've made #129 to implement the above
